services:
  notification-service:
    build:
      context: .
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    container_name: "not-service"
    env_file:
      - .env
    networks:
      - global-network
networks:
  global-network:
    name: global-network
    external: true
    driver: bridge