services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    container_name: "not-service"
    networks:
      - global-network
networks:
  global-network:
    name: global-network
    external: true
    driver: bridge