spring:
  profiles:
    active: default
  application:
    name: ${SPRING_APP_NAME:notification-service}
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: notifications
  mail:
    host: mailsender
    port: 1025
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASS}
  config:
    import: file:env.properties
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: 5672
    queues:
      fp-exchange-name: "notifications"
      fp-qname: "forgotPasswordQueue"
      cp-qname: "changePassword"
      aa-qname: "activateAccount"
      cancel-reservation-qname: "cancelReservationQueue"
      delete-pending-user-queue: "deletePendingUserQueue"
      delete-pending-balance-queue: "deletePendingBalanceQueue"
      verify-email-queue: "verifyEmailQueue"
      disable-job-queue: "disableJobQueue"
      enable-job-queue: "enableJobQueue"
      cancel-job-reservations-queue: "cancelJobReservationsQueue"
      disable-job-reviews-queue: "disableJobReviewsQueue"
      enable-job-reviews-queue: "enableJobReviewsQueue"
      sm-qname: "sendMail"
      new-reservation-queue: "newReservationQueue"
      reservation-edited-queue: "reservationEditedQueue"
      reservation-accepted-queue: "reservationAcceptedQueue"
      reservation-rejected-queue: "reservationRejectedQueue"
      user-ban-queue: "userBanQueue"
      user-unban-queue: "userUnbanQueue"

server:
  port: 8087
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
management:
  endpoints:
    web:
      exposure:
        include=*:

scheduler:
  failed_notifications:
    time: 60000