spring:
  profiles:
    active: default
  application:
    name: ${SPRING_APP_NAME:notification-service}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8888
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
management:
  endpoints:
    web:
      exposure:
        include=*: