apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: hah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: notification-service-container
          image: europe-west3-docker.pkg.dev/gd-gcp-internship-dc/hah-registry/notification-service:initial
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: MAIL_PASS
            - name: ADMIN_MAIL
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: ADMIN_MAIL
            - name: BASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: NOTIFICATION_API_KEY
            - name: AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: AUTH_API_KEY
            - name: EUREKA_SERVICE_URL
              value: http://eureka-naming-server-service:8761/eureka
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"