apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
  namespace: hah
spec:
  selector:
    app: notification-service
  ports:
    - name: gateway
      protocol: TCP
      port: 8087
  type: ClusterIP